<?xml version="1.0" ?>


<robot name="giraffe_robot"  xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- parameters -->
    <xacro:property name="ceiling_height" value="4.0"/>
    <xacro:property name="box_heigth" value="0.05"/>
    <xacro:property name="link_radius" value="0.05"/>
    <xacro:property name="prismatic_length" value="5.5"/>  <!-- prismatic range -->
    <xacro:property name="wrist_length" value="1"/>
    <xacro:property name="wrist2_radius" value="0.015"/>

    <!-- materials -->
    <material name="Blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="Grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <material name="White">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="Black">
        <color rgba="0 0 0 1"/>
    </material>

    <!-- params for inertia -->
    <!-- chosen material for the robot: aluminum. ABS plastic for microphone -->
    <xacro:property name="density_aluminum" value="2700.0"/>  <!-- density to compute mass (kg/m^3)-->
    <xacro:property name="density_plastic" value="1030.0"/>  <!-- density to compute mass (kg/m^3)-->
    <!-- masses of robot elements: density*volume -->
    <xacro:property name="base_joint_mass" value="${density_aluminum * (4/3)*pi*pow(link_radius, 3)}"/>    <!-- unique sphere volume for joint 1 and 2 -->
    <xacro:property name="prismatic_mass" value="${density_aluminum * pi*pow(link_radius, 2)*prismatic_length}"/>     <!-- sphere volume -->
    <xacro:property name="wrist1_joint_mass" value="${density_aluminum* pi*pow(link_radius, 2)*wrist_length}"/>  <!-- cylinder volume -->
    <xacro:property name="wrist1_mass" value="${density_aluminum* pi*pow(link_radius, 2)*wrist_length}"/>        <!-- cylinder volume -->
    <xacro:property name="wrist2_joint_mass" value="${density_aluminum* (4/3)*pi*pow(wrist2_radius, 3)}"/>  <!-- sphere volume -->
    <xacro:property name="mic_mass" value="${density_plastic* ((4/3)*pi*pow(0.03, 3) + pi*pow(0.02, 2)*0.1)}"/>    <!-- cylinder+sphere volume -->



    <link name="world"/>
   
   <!--floor 5x12 -->
    <link name="floor">
    <visual>
        <geometry>
        <box size="5 12 0.01"/> <!-- thin plane -->
        </geometry>
        <origin xyz="2.5 6 -0.005" rpy="0 0 0"/>    <!-- in -z to perfectly center it -->
        <material name="Grey"/>
    </visual>
    </link >

    <joint name="world_floor" type="fixed">
        <parent link="world"/>
        <child link="floor"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- base link (on the ceiling) -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="0.2 0.2 ${box_heigth}"/>
            </geometry>
            <material name="Grey"/>
        </visual>
    </link>
    
    <!-- world reference set at the center of the ceiling-->
    <joint name="world_base" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="2.5 6.0 ${ceiling_height}" rpy="0 0 0"/>
    </joint>

    <!-- yaw link (z axis) and joint -->
    <link name="yaw_link">
        <visual>
            <geometry>
                <sphere radius="${link_radius}"/>
            </geometry>
            <material name="White"/>
        </visual>

        <inertial>
            <mass value="${base_joint_mass/2}"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/> <!-- position in the center --> 
            <inertia ixx="${(2.0/5.0) * base_joint_mass * pow(link_radius, 2)}" 
            ixy="0.0" 
            ixz="0.0" 
            iyy="${(2.0/5.0) * base_joint_mass * pow(link_radius, 2)}" 
            iyz="0.0" 
            izz="${(2.0/5.0) * base_joint_mass * pow(link_radius, 2)}"/>   <!-- inertia formula for full spheres -->
        </inertial>
    </link>

    <joint name="yaw_joint" type="revolute">
        <parent link="base_link"/>
        <child link="yaw_link"/>
        <origin xyz="0.0 0.0 -${link_radius+box_heigth/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-${pi}" upper="${pi}" effort="10" velocity="1"/>
    </joint>

    <!-- pitch link (y axis) and joint -->
    <link name="pitch_link">
        <visual>
            <geometry>
                <sphere radius="${link_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <material name="White"/>
        </visual>

        <inertial>
            <mass value="${base_joint_mass/2}"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/> <!-- position in the center --> 
            <inertia ixx="${(2.0/5.0) * base_joint_mass * pow(link_radius, 2)}" 
            ixy="0.0" 
            ixz="0.0" 
            iyy="${(2.0/5.0) * base_joint_mass * pow(link_radius, 2)}" 
            iyz="0.0" 
            izz="${(2.0/5.0) * base_joint_mass * pow(link_radius, 2)}"/>   <!-- inertia formula for spheres -->
        </inertial>
    </link>

    <joint name="pitch_joint" type="revolute">
        <parent link="yaw_link"/>
        <child link="pitch_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-${pi/2}" upper="${pi/2}" effort="10" velocity="1"/>
    </joint>


    <!-- prismatic link and joint -->
    <link name="prismatic_link">
        <visual>
            <geometry>
                <cylinder length="${prismatic_length}" radius="${link_radius}"/>
            </geometry>
            <origin xyz="0 0 -${link_radius}" rpy="0 0 0"/>
            <material name="White"/>
        </visual>

        <inertial>
            <mass value="${prismatic_mass}"/>
            <origin xyz="0.0 0.0 -${prismatic_length/2}" rpy="0 0 0"/> <!-- position in the center --> 
            <inertia ixx="${(1.0/12.0) * prismatic_mass * (3*pow(link_radius,2) + pow(prismatic_length, 2))}" 
            ixy="0.0" 
            ixz="0.0" 
            iyy="${(1.0/12.0) * prismatic_mass * (3*pow(link_radius,2) + pow(prismatic_length, 2))}" 
            iyz="0.0" 
            izz="${(1.0/2.0) * prismatic_mass * pow(link_radius, 2)}"/>   <!-- inertia formula for cylinders (cylinder axis along z) -->
        </inertial>                                                       <!-- izz=1/2mr^2 , ixx=iyy=1/12m(3r^2+L^2)-->
    </link>

    <joint name="prismatic_joint" type="prismatic">
        <parent link="pitch_link"/>
        <child link="prismatic_link"/>
        <origin xyz="0 0 -${prismatic_length/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="0.0" upper="${prismatic_length}" effort="100" velocity="0.5"/>
    </joint>


    <!-- wrist1 link and joint -->
    <link name="wrist1_link">
        <visual>
            <geometry>
                <cylinder length="${wrist_length}" radius="${link_radius}"/>
            </geometry>
            <origin xyz="0 0 -${wrist_length/2}" rpy="0 0 0"/>
            <material name="White"/>
        </visual>

        <inertial>
            <mass value="${wrist1_mass}"/>
            <origin xyz="0.0 0.0 -${wrist_length/2}" rpy="0 0 0"/> <!-- position in the center --> 
            <inertia ixx="${(1.0/12.0) * wrist1_mass * (3*pow(link_radius,2) + pow(wrist_length, 2))}" 
            ixy="0.0" 
            ixz="0.0" 
            iyy="${(1.0/12.0) * wrist1_mass * (3*pow(link_radius,2) + pow(wrist_length, 2))}" 
            iyz="0.0" 
            izz="${(1.0/2.0) * wrist1_mass * pow(link_radius, 2)}"/>   <!-- inertia formula for cylinders (cylinder axis along z) -->
        </inertial>          
    </link>

    <joint name="wrist1" type="revolute">
        <parent link="prismatic_link"/>
        <child link="wrist1_link"/>
        <origin xyz="0 0 -${prismatic_length/2}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-${pi/2}" upper="${pi/2}" effort="5" velocity="1"/>
    </joint>

    <!-- wrist2 link and joint -->
    <link name="wrist2_link">
        <visual>
            <geometry>
                <sphere radius="${wrist2_radius}"/>
            </geometry>
            <material name="Black"/>
        </visual>

        <inertial>
            <mass value="${wrist2_joint_mass}"/>
            <origin xyz="0.0 0.0 -${wrist2_radius/2}" rpy="0 0 0"/> <!-- position in the center --> 
            <inertia ixx="${(2.0/5.0) * wrist2_joint_mass * pow(wrist2_radius, 2)}" 
            ixy="0.0" 
            ixz="0.0" 
            iyy="${(2.0/5.0) * wrist2_joint_mass * pow(wrist2_radius, 2)}" 
            iyz="0.0" 
            izz="${(2.0/5.0) * wrist2_joint_mass * pow(wrist2_radius, 2)}"/>   <!-- inertia formula for spheres -->
        </inertial>
    </link>

    <joint name="wrist2" type="revolute">
        <parent link="wrist1_link"/>
        <child link="wrist2_link"/>
        <origin xyz="0 0 -${wrist_length}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-${pi/2}" upper="${pi/2}" effort="5" velocity="1"/>
    </joint>

    <!-- microphone (end effector) -->
     <link name="microphone">
        <visual>
            <geometry>
                <cylinder length="0.1" radius="0.02"/>
            </geometry>
            <origin xyz="0 0 0.11" rpy="0 0 0"/>
            <material name="Grey"/>
        </visual>
        <visual>
            <geometry>
                <sphere radius="0.03"/>
            </geometry>
            <origin xyz="0 0 0.03" rpy="0 0 0"/>
            <material name="Black"/>
        </visual>

        <inertial>      <!-- to simplify we approximate the inertia computation to a cylinder with the mic sphere's radius -->
            <mass value="${mic_mass}"/>
            <origin xyz="0 0 -0.08" rpy="0 0 0"/> <!-- center in the center of the approx cylinder (sphere radius+cylinder length)/2 -->
            <inertia
                ixx="${(1.0/12.0) * mic_mass * (3*pow(0.03,2) + pow(0.08,2))}"
                ixy="0.0"
                ixz="0.0"
                iyy="${(1.0/12.0) * mic_mass * (3*pow(0.03,2) + pow(0.08,2))}"
                iyz="0.0"
                izz="${(1.0/2.0) * mic_mass * pow(0.03,2)}"/>
        </inertial>
    </link>

    <joint name="mic_frame" type="fixed">
        <parent link="wrist2_link"/>
        <child link="microphone"/>
        <origin xyz="0 0 -0.175" rpy="0 0 0"/>
    </joint>

</robot>
